services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=lionsden
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  